#!/bin/bash

#System Information

userName=$(whoami)
dateTime=$(date)
hostName=$(hostname)
source /etc/os-release
osName="$NAME $VERSION"
upTime=$(uptime -p)

#Hardware Information

cpuInfo=$(grep -m 1 'model name' /proc/cpuinfo | awk -F': ' '{print $2}')
cpuSpeed=$(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F': ' '{print $2 " MHz"}')
ramSize=$(free -h | grep Mem | awk '{print $2}')
disks=$(lsblk -d -o MODEL,SIZE)
videoCard=$(lshw -class display | grep 'product:' | awk -F': ' '{print $2}')

#Network Information

FQDN=$(hostname -f)
hostIP=$(hostname -I |awk '{print $1}')
gateway=$(ip route | grep default | awk '{print $3}')
DNS=$(grep 'nameserver' /etc/resolv.conf | awk '{print $2}' | head -n 1)
networkCard=$(lshw -class network | grep 'product:' | awk -F': ' '{print $2}')
interfaceIP=$(ip a | grep inet | grep -v 127.0.0.1 | awk '{print $2}' | head -1)

#System Status

loggedInUsers=$(who | awk '{print $1}' | paste -sd, -)
diskSpace=$(df -h --output=source,pcent | grep -v Use | paste -sd, -)
processCount=$(ps aux | wc -l)
loadAverage=$(uptime | awk -F'load average:' '{print $2}' | xargs)
memoryAllocation=$(free -h)
listeningPorts=$(ss -tuln | grep LISTEN | awk '{print $5}' | cut -d: -f2 | paste -sd, -)
ufwRules=$(sudo ufw status)

#Display Report

cat <<EOF

System Report generated by $userName, $dateTime

System Information
__________________

Hostname: $hostName
OS: $osName
Uptime: $upTime

Hardware Information
____________________

CPU: $cpuInfo
Speed: $cpuSpeed
RAM: $ramSize
Disk(s): $disks
Video: $videoCard

Network Information
___________________

FQDN: $FQDN
Host Address: $hostIP
Gateway IP: $gateway
DNS Server: $DNS

Interface Name: $networkCard
IP Address: $interfaceIP

System Status
_____________

Users Logged In: $loggedInUsers
Disk Space: $diskSpace
Process Count: $processCount
Load Averages: $loadAverage
Memory Allocation: $memoryAllocation
Listening Network Ports: $listeningPorts
UFW Rules:
$ufwRules

EOF


