#!/bin/bash

#System Information

USERNAME=$(whoami)
DATETIME=$(date)
HOSTNAME=$(hostname)
source /etc/os-release
DISTRO="$NAME $VERSION"
UPTIME=$(uptime -p)

#Hardware Information

CPU_INFO=$(grep -m 1 'model name' /proc/cpuinfo | awk -F': ' '{print $2}')
CPU_SPEED=$(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F': ' '{print $2 " MHz"}')
RAM_SIZE=$(free -h | grep Mem | awk '{print $2}')
DISKS=$(lsblk -d -o MODEL,SIZE)
VIDEO_CARD=$(lshw -class display | grep 'product:' | awk -F': ' '{print $2}')

#Network Information

FQDN=$(hostname -f)
HOST_IP=$(hostname -I |awk '{print $1}')
GATEWAY=$(ip route | grep default | awk '{print $3}')
DNS=$(grep 'nameserver' /etc/resolv.conf | awk '{print $2}' | head -n 1)
NETWORK_CARD=$(lshw -class network | grep 'product:' | awk -F': ' '{print $2}')
INTERFACE_IP=$(ip a | grep inet | grep -v 127.0.0.1 | awk '{print $2}' | head -1)

#System Status

LOGGED_IN_USERS=$(who | awk '{print $1}' | paste -sd, -)
DISK_SPACE=$(df -h --output=source,pcent | grep -v Use | paste -sd, -)
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGE=$(uptime | awk -F'load average:' '{print $2}' | xargs)
MEMORY_ALLOCATION=$(free -h)
LISTENING_PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | cut -d: -f2 | paste -sd, -)
UFW_RULES=$(sudo ufw status)

#Display Report

cat <<EOF

System Report generated by $USERNAME, $DATETIME

System Information
__________________

Hostname: $HOSTNAME
OS: $DISTRO
Uptime: $UPTIME

Hardware Information
____________________

CPU: $CPU_INFO
Speed: $CPU_SPEED
RAM: $RAM_SIZE
Disk(s): $DISKS
Video: $VIDEO_CARD

Network Information
___________________

FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY
DNS Server: $DNS

Interface Name: $NETWORK_CARD
IP Address: $INTERFACE_IP

System Status
_____________

Users Logged In: $LOGGED_IN_USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGE
Memory Allocation: $MEMORY_ALLOCATION
Listening Network Ports: $LISTENING_PORTS
UFW Rules:
$UFW_RULES

EOF


